#!/bin/bash

# registration with rhn
sh /home/hus/Downloads/bootstrap_lab.sh

yum -y install nfs-utils
yum -y install samba 
yum -y install sssd-ad 
yum -y install cyrus-sasl-gssapi 

yum -y install sssd-krb5
yum -y install sssd-ldap

yum -y install sssd-client.i686 

# enable kerberos
authconfig --enablekrb5 --update --krb5realm=USASK.CA --krb5kdc=usaskdc5.usask.ca,usaskdc2.usask.ca,usaskdc6.usask.ca 

#setup files required by sssd and nfs
if [ ! -d "/mnt/eceappinstall" ]; then
   mkdir -p /mnt/eceappinstall
fi

mount oneplus2:/var/www/html/repo /mnt/eceappinstall 

\cp /mnt/eceappinstall/conffiles/krb5.conf /etc/ 
\cp /mnt/eceappinstall/conffiles/smb.conf /etc/samba/ 
hn=$(hostname) 
#added in case hostname comes up with usask.ca or USASK.CA
if [[ $hn == *"usask.ca"* ]]
then
  hn=${hn//.usask.ca/}
elif [[ $hn == *"USASK.CA"* ]];
then
  hn=${hn//.USASK.CA/}
fi
nmcli general hostname $hn
systemctl restart systemd-hostnamed
net ads join -U ana095 createcomputer=ResearchComputingOU/PHYOU
\cp /mnt/eceappinstall/conffiles/nfs /etc/sysconfig/
\cp /mnt/eceappinstall/conffiles/nsswitch.conf /etc/
\cp /mnt/eceappinstall/conffiles/sssd_phy.conf /etc/sssd/sssd.conf 
\cp /mnt/eceappinstall/conffiles/idmapd.conf /etc/ 

chmod 700 /etc/sssd/sssd.conf 

systemctl enable nfs-client.target 
systemctl start nfs-client.target
systemctl enable sssd.service 
systemctl start sssd.service 
sleep 5
systemctl restart sssd.service

echo "nfsfiles.usask.ca:/home    /home    nfs    sec=krb5,exec,vers=3,_netdev   0  0" >> /etc/fstab

mount -a

\cp /mnt/eceappinstall/conffiles/profile /etc/

# rhn stuff
yum -y install rhncfg-actions
yum -y install rhncfg
yum -y install rhncfg-client
mkdir -p /etc/sysconfig/rhn/allowed-actions/script
touch /etc/sysconfig/rhn/allowed-actions/script/run
yum -y install osad
systemctl start osad
systemctl enable osad

# serial permissioin from IJM
yum -y install minicom
chgrp dialout /usr/bin/minicom
chmod g+s /usr/bin/minicom

cd /tmp
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh epel-release-latest-7.noarch.rpm
rm epel-release-latest-7.noarch.rpm
yum -y install ckermit
chgrp dialout /usr/bin/kermit
chmod g+s /usr/bin/kermit

# This is not working after a reboot
chmod 666 /dev/ttyS0
chmod 666 /dev/ttyS1
chmod 666 /dev/ttyS2
chmod 666 /dev/ttyS3

# Permanent solution for reboot
touch /etc/udev/rules.d/60-serial.rules
echo "KERNEL=="ttyS0", MODE="0666"" >> /etc/udev/rules.d/60-serial.rules
echo "KERNEL=="ttyS1", MODE="0666"" >> /etc/udev/rules.d/60-serial.rules
echo "KERNEL=="ttyS2", MODE="0666"" >> /etc/udev/rules.d/60-serial.rules
echo "KERNEL=="ttyS3", MODE="0666"" >> /etc/udev/rules.d/60-serial.rules

# This finally works
cd 
crontab -l > mycron
echo "@reboot chmod 666 /dev/ttyS*" >> mycron
crontab mycron
rm -f mycron


# I did the following via rhn on all 13 machines on Aug. 30, 2017
#################################################################
## display hostname on lock screen###############################
touch /etc/dconf/profile/gdm
echo "user-db:user" > /etc/dconf/profile/gdm
echo "system-db:gdm" >> /etc/dconf/profile/gdm
echo "file-db:/usr/share/gdm/greeter-dconf-defaults" >> /etc/dconf/profile/gdm

touch /etc/dconf/db/gdm.d/01-banner-message
echo "[org/gnome/login-screen]" > /etc/dconf/db/gdm.d/01-banner-message
echo "banner-message-enable=true" >> /etc/dconf/db/gdm.d/01-banner-message
hn=`hostname`
if [[ $hn == *"usask.ca"* ]]
then
  hn=${hn//.usask.ca/}
elif [[ $hn == *"USASK.CA"* ]];
then
  hn=${hn//.USASK.CA/}
fi
hn+=".usask.ca"
echo "banner-message-text='$hn'" >> /etc/dconf/db/gdm.d/01-banner-message

dconf update
#################################################################

yum -y install texmaker
yum -y install emacs
yum -y install joe
yum -y install vim-X11
yum -y install kwrite
yum -y groupinstall kde-desktop
yum -y install tftp
yum -y install ftp

### Setup env and path ######################################### 
touch /etc/profile.d/ep413.sh
echo "export PATH=\$PATH:/opt/rtems-4.11/bin" > /etc/profile.d/ep413.sh
echo "export RTEMS_CUSTOM=/opt/rtems-4.11/make/custom" >> /etc/profile.d/ep413.sh
echo "export RTEMS_MAKEFILE_PATH=/opt/rtems-4.11/m68k-rtems4.11/uC5282" >> /etc/profile.d/ep413.sh
echo "export PROJECT_ROOT=/opt/rtems-4.11" >> /etc/profile.d/ep413.sh

### kde as only option for login ##############################
rpm -e gnome-session-xsession gnome-classic-session
systemctl restart gdm.service

### printer and papercut ######################################
yum -y install foomatic hplip
lpadmin -p PhysicsLounge -v smb://arts-lab-spool/Physics_Lounge -m foomatic:Lexmark-T640-Postscript.ppd -o auth-info-required=username,password -E
lpadmin -d PhysicsLounge

cd 
wget https://www.cs.usask.ca/cpas/pcclient-linux.zip
unzip pcclient-linux.zip
mv pcclient-linux /opt/
echo "sh /opt/pcclient-linux/pc-client-linux.sh &" >> /etc/profile

reboot
