#!/bin/bash

# registration with rhn
sh /home/hus/Downloads/bootstrap_lab.sh

yum -y install nfs-utils
yum -y install samba 
yum -y install sssd-ad 
yum -y install cyrus-sasl-gssapi 

yum -y install sssd-krb5
yum -y install sssd-ldap

yum -y install sssd-client.i686 

# enable kerberos
authconfig --enablekrb5 --update --krb5realm=USASK.CA --krb5kdc=usaskdc5.usask.ca,usaskdc2.usask.ca,usaskdc6.usask.ca 

#setup files required by sssd and nfs
if [ ! -d "/mnt/eceappinstall" ]; then
   mkdir -p /mnt/eceappinstall
fi

mount oneplus2:/var/www/html/repo /mnt/eceappinstall 

\cp /mnt/eceappinstall/conffiles/krb5.conf /etc/ 
\cp /mnt/eceappinstall/conffiles/smb.conf /etc/samba/ 
hn=$(hostname) 
#added in case hostname comes up with usask.ca or USASK.CA
if [[ $hn == *"usask.ca"* ]]
then
  hn=${hn//.usask.ca/}
elif [[ $hn == *"USASK.CA"* ]];
then
  hn=${hn//.USASK.CA/}
fi
nmcli general hostname $hn
systemctl restart systemd-hostnamed
net ads join -U ana095 createcomputer=ResearchComputingOU/PHYOU
\cp /mnt/eceappinstall/conffiles/nfs /etc/sysconfig/
\cp /mnt/eceappinstall/conffiles/nsswitch.conf /etc/
\cp /mnt/eceappinstall/conffiles/sssd_phy.conf /etc/sssd/sssd.conf 
\cp /mnt/eceappinstall/conffiles/idmapd.conf /etc/ 

chmod 700 /etc/sssd/sssd.conf 

systemctl enable nfs-client.target 
systemctl start nfs-client.target
systemctl enable sssd.service 
systemctl start sssd.service 
sleep 5
systemctl restart sssd.service

echo "nfsfiles.usask.ca:/home    /home    nfs    sec=krb5,exec,vers=3,_netdev   0  0" >> /etc/fstab

mount -a

\cp /mnt/eceappinstall/conffiles/profile /etc/

yum -y install gcc
yum -y install gcc-c++
yum -y install bison
yum -y install patch
yum -y install flex
yum -y install texinfo
yum -y install python-devel
yum -y install mkdirhier

cd
wget ftp://kermit.columbia.edu/kermit/archives/cku302.zip
mkdir cku302
mv cku302.zip cku302
cd cku302
unzip cku302.zip
make -j3 linux

cd
wget http://plit.de/asem-51/asem51-1.3-ELF.tar.gz
tar -zxvf asem51-1.3-ELF.tar.gz
cd asem51
sh install.sh

cd
mkdir -p development/rtems/rsb
cd development/rtems/rsb
git clone git://git.rtems.org/rtems-source-builder.git
cd rtems-source-builder
cd rtems
../source-builder/sb-set-builder --prefix=/opt/development/rtems/4.12 4.12/rtems-m68k

cd
wget https://ftp.rtems.org/pub/rtems/releases/4.10/4.10.2/rtems-4.10.2.tar.bz2
tar xjf rtems-4.10.2.tar.bz2
export PATH=/opt/development/rtems/4.12:$PATH
cd rtems-4.10.2
mkdir b-sis
cd b-sis
../configure --target=m68k-rtems4.12 --enable-rtemsbsp='uC5282'
make
